language: node_js
node_js:
- '0.10'
before_install:
- npm install -g -q bower
- npm install -g -q grunt-cli
- npm install -g karma-cli
- npm install -g karma-jasmine
- npm install -g karma-chrome-launcher
install:
- npm install -q
- bower install

