before_install:
- npm install -g -q bower
- npm install -g -q grunt-cli
- npm install -g -q protractor
- webdriver-manager update
- webdriver-manager start
install:
- npm install -q
- bower install
language: node_js
node_js:
- '0.10'
